name: Deploy .NET to Azure App Service

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # ajuste para a versão que seu projeto usa

      # 3. Restaurar dependências
      - name: Restore dependencies
        run: dotnet restore

      # 4. Build
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # 5. Testes (opcional, pode remover se quiser rapidez no protótipo)
      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      # 6. Publicar (gera arquivos prontos para deploy)
      - name: Publish
        run: dotnet publish -c Release -o ./publish

      # 7. Deploy no Azure (staging ou produção, conforme branch)
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ github.ref == 'refs/heads/main' && 'SEU_APP_PROD' || 'SEU_APP_STAGING' }}
          publish-profile: ${{ github.ref == 'refs/heads/main' && secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PRODUCTION || secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}
          package: ./publish
